apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: mean_eks_demo
    app.kubernetes.io/instance: mean_eks_demo-instance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl
  name: mean_eks_demo
spec:
  selector:
    app: mean_eks_demo
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 4040
